### PR TITLE
Promises for brunch

### PR DESCRIPTION
**Pull request by ghostd**
Hi,

Here is a patch to replace (most of) callbacks by promises.

I only tested it against a small project (3 js, 2 scss). this patch needs to be tested with an actual project (especially to check the performance).

### CODE REVIEW

**Comment by paulmillr** [comment]
That's a good one. Thanks Vincent! I'll test it on a real project.

**Comment by paulmillr** [comment]
My initial suggestion would be to move away from bluebird to native promises.

**Comment by ghostd** [comment]
Here is a version without bluebird

Since i removed 'async-each' on this branch, i think we'll need to add a 3rd party dependency to get back some performance. (check around my 'Array.reduce' and 'Promise.all' calls in the code)

**Comment by paulmillr** [comment]
It seems like we have quite a lot cases where we simply do `reject` if there's an async error and `resolve` if no error. Could you please make a util for this purpose like `promisify` in bluebird?

```javascript
const promisify = (fn) => {
  return function() {
    return new Promise((resolve, reject) =>
      const args = [].slice.call(arguments);
      args.push((error, data) => {
        if (error != null) return reject(error);
        resolve(data);
      });
      fn.apply(null, args);
    });
  };
};

const read = promisify(fs.readFile);
```

**Comment by paulmillr** [comment]
Thanks — will check this tomorrow.

**Comment by paulmillr** [comment]
Doesn't work with a project.

```
30 Oct 22:04:44 - error: [TypeError: components.sort is not a function]
```

Seeing this in the console.

**Comment by paulmillr** [comment]
There seem to be no speed penalty while using this branch. Interesting.

**Comment by paulmillr** [comment]
Last-minute change: Could you please squash all commits into one? I think we're good to merge this.

@es128 ?

**Comment by es128** [comment]
+0 meh

https://twitter.com/henrikjoreteg/status/661053038690340865

I don't necessarily agree with that sentiment 100%, but in the context of this PR and what motivated it I do.

**Comment by paulmillr** [comment]
Totally agree, there is no simplification here.

**Comment by paulmillr** [comment]
ideally there would just be `async` / `await` and `yield` shit, don't know how far away we are from there.

**Comment by ghostd** [comment]
i agree these commits does not simplify the code.
So do we drop this PR ?

**Comment by paulmillr** [comment]
No. Let's keep it around. Could you squash all commits into one please?

**Comment by paulmillr** [comment]
gh-1036

**Comment by paulmillr** [comment]
@ghostd thanks, it's in master now.

**Pull request closed without merging**
