### PR TITLE
Print warnings when plugins take too long to process

### PR DESCRIPTION
**Pull request by goshakkk**
Closes GH-1402

### CODE REVIEW

**Comment by paulmillr** [comment]
What about old and slow machines while doing a big uglifyjs pass on a js file?

**Comment by goshakkk** [comment]
Well, what value do you think will be reasonable?

**Comment by paulmillr** [comment]
Don't know. Just saying. We have for example at least two slow servers in production. They take at least 4x more time vs local compilations.

**Comment by es128** [comment]
How about just print status messages a few times at intervals like 15 secs, 30 secs, then finally fully timeout after a pretty long time. 3 minutes maybe?

**Comment by paulmillr** [comment]
I don't think we should time out at all. There are some cases that prolong the build a lot.

Let's keep it simple.

**Comment by es128** [comment]
Is part of the purpose of this not to prevent unmonitored automated build systems from hanging?

Although I guess they tend to have their own built-in mechanisms for detecting and intervening on runaway processes.

**Comment by goshakkk** [comment]
Ok, I updated to make it just print a warning every 15s without ever rejecting.

**Pull request merged**
