### PR TITLE
Fix BRUNCH_FORKED_PROCESS global variable

### PR DESCRIPTION
**Pull request by marcioj**
I added the BRUNCH_FORKED_PROCESS variable in the previous PR but your usage was incorrect, so the reload message will never trigger. Sorry for that.

### CODE REVIEW

**Comment by paulmillr** [comment]
fails tests

**Comment by marcioj** [comment]
@paulmillr the error seems something related to npm cache and just failed on one of the 4 jobs. Could you please trigger a new build on travis to see if it passes?

**Comment by paulmillr** [comment]
Still broken @marcioj

**Comment by marcioj** [comment]
I tested here (linux) with both node 5 and 6 and all tests passed. This was also true on Travis, but OSX sometimes fail. I'm unable to test in an OSX right now through. But looking the previous builds node 6 passed on OSX in the first run, but failed on the second. It might be some synchronization issue that happens sometimes.

**Pull request merged**
