### PR TITLE
Split up deppack into several focused files

### PR DESCRIPTION
**Pull request by goshakkk**

### CODE REVIEW

**Comment by paulmillr** [comment]
Global variables are smelly. Can we put everything into mediator or so?

**Comment by goshakkk** [comment]
@paulmillr done

**Comment by tmjoen** [comment]
Did this break import paths in deppack?

Straight imports like `import "lib"` or `import {Foo} from "lib"` work, but  when I do `import {Foo} from "lib/module"` brunch errors with:

```
/usr/local/lib/node_modules/brunch/lib/deppack/resolve.js:51
        const topLevel = modules.getModuleRootName(mod);
                                 ^

TypeError: modules.getModuleRootName is not a function
  at /usr/local/lib/node_modules/brunch/lib/deppack/resolve.js:51:34
  at /usr/local/lib/node_modules/brunch/node_modules/browser-resolve/index.js:264:24
  at /usr/local/lib/node_modules/brunch/node_modules/resolve/lib/async.js:46:14
  at process (/usr/local/lib/node_modules/brunch/node_modules/resolve/lib/async.js:173:43)
  at ondir (/usr/local/lib/node_modules/brunch/node_modules/resolve/lib/async.js:188:17)
  at load (/usr/local/lib/node_modules/brunch/node_modules/resolve/lib/async.js:69:43)
  at onex (/usr/local/lib/node_modules/brunch/node_modules/resolve/lib/async.js:92:31)
  at /usr/local/lib/node_modules/brunch/node_modules/resolve/lib/async.js:22:47
  at FSReqWrap.oncomplete (fs.js:82:15)
```

on master, was testing the #1151 fix.

**Comment by goshakkk** [comment]
@tmjoen I've just submitted a fix for this in #1156.

Note, however, that in `deppack/resolve`, `modules.getModuleRootName` is called to generate a friendly error message about not being able to load the given path. (That could be due to not all dependencies installed or to loading a non-existing module.)

**Comment by tmjoen** [comment]
Ah, I see. Thanks for the fix!

**Pull request merged**
