### PR TITLE
Fix scripts

### PR DESCRIPTION
**Pull request by yavorsky**

### CODE REVIEW

**Comment by es128** [comment]
No, why? We want the code compiled prior to publishing to npm, no need to have every user do it locally.

**Comment by yavorsky** [comment]
@es128 Ok, but in .gitignore I found `lib/`. So, after `npm i -g brunch` there isn't lib/ in `/usr/local/lib/node_modules/brunch`.

**Comment by es128** [comment]
It isn't in npmignore though. Why is gitignore relevant?

**Comment by yavorsky** [comment]
@es128  Yes, of course, but there is problems when we want to use edge version from github. ex. `sudo npm install -g https://github.com/brunch/brunch/tarball/master`.

**Comment by es128** [comment]
Ah that's right. I had forgotten why we had it this way. Still, perhaps the `postinstall` could be set to run `preinstall` if `lib` is absent, otherwise noop.

**Comment by paulmillr** [comment]
we had the good setup.js script — perphaps we need to bring it back.

**Pull request closed without merging**
