### PR TITLE
Badges in readme.md

### PR DESCRIPTION
**Pull request by PeterDaveHello**

### CODE REVIEW

**Comment by es128** [comment]
Thanks, but I don't think these are adding any value here. Brunch does not currently have a robust test suite, and considering it is a tool, not a module people depend upon in their production apps, I don't think the info provided by the other badges would be useful at this point.

**Comment by PeterDaveHello** [comment]
You can easily know that there is security issue in dependencies ...

[devDependency Status](https://david-dm.org/brunch/brunch#info=devDependencies)

**Comment by es128** [comment]
> it is a tool, not a module people depend upon in their production apps

**Comment by PeterDaveHello** [comment]
Fine.

**Pull request closed without merging**
