### PR TITLE
Add 'detectProcess' flag to npm config.

### PR DESCRIPTION
**Pull request by facboy**
For https://github.com/brunch/brunch/issues/1378

### CODE REVIEW

**Comment by paulmillr** [comment]
I think we want a more general way of excluding packages. Like: `npm: ignored: ['process']`

**Comment by goshakkk** [comment]
Auto-detected shims are about the only case I can think of, so why be more generic?

**Comment by facboy** [comment]
I actually started out with the generic case but decided to keep things simpler.  I can imagine a scenario when a package might be included by another third-party package and I might want to exclude it, but don't really have a concrete use case.

**Comment by paulmillr** [comment]
Could we change it to `includeProcess`? Let's go with that. @facboy

**Comment by facboy** [comment]
arguably that is less accurate, the flag disables the auto-detection of `process`.  if a package explicitly requires `process` it will still be included, which might surprise somebody if they've put `includeProcess: false`.

**Comment by goshakkk** [comment]
@paulmillr, @facboy is correct — this just toggles auto-detection so `detectProcess` seems more apropriate.

**Comment by ferhatelmas** [comment]
> I think we want a more general way of excluding packages. Like: npm: ignored: ['process']

How can we exclude some packages for prod ? 

For example, let's say we require [why-did-you-update](https://www.npmjs.com/package/why-did-you-update) and enable it for dev. For sure, it's not enabled for prod but it's still bundled into vendor.

**Comment by goshakkk** [comment]
@ferhatelmas we currently don't do that... but yeah, it kind of makes sense, I'll add it to our backlog

**Pull request merged**
