### PR TITLE
ECMAScript 6 rewrite

### PR DESCRIPTION
**Pull request by paulmillr**

### CODE REVIEW

**Comment by paulmillr** [comment]
@es128 my intention is to merge this today. Please review!

**Comment by es128** [comment]
I'm confused. What's the distinction between what's been committed to master and this PR?

**Comment by es128** [comment]
No babel? You intend to require users to be on Node v4 to use this? On a minor version release?

**Comment by frankrousseau** [comment]
Sad to see one of my favorite project leaving Coffeescript. Whatever I hope it will bring you more contributions!

**Comment by paulmillr** [comment]
> You intend to require users to be on Node v4 to use this

Yeah. 1.9: node v4+. 1.8: node 0.12 / 0.10 / 0.8. I think this is acceptable. We can backport some stuff.

**Comment by paulmillr** [comment]
> What's the distinction between what's been committed to master and this PR

Master still has coffeescript. This one only has JS.

**Comment by es128** [comment]
> 1.9: node v4+.

It's not quite semver-friendly, but I guess we've selectively violated semver in various ways all along. We can look toward 2.0 to start trying to comply better.

> Master still has coffeescript.

Ah ok, I only saw that all the commits were labeled with ES6. It's just prep work in advance of the conversion?

**Comment by paulmillr** [comment]
> It's just prep work in advance of the conversion

Yep.

**Comment by paulmillr** [comment]
Another option is to name the release 2.0. Rapid version increases seem to be in fashion nowadays (Linux, Chrome, Node).

**Comment by es128** [comment]
> Another option is to name the release 2.0

I think that's better. A future major rewrite/refactor can become 3.0. Or whatever. Just a major bump, no significant relevance to the numbers.

**Comment by es128** [comment]
Should change the travis config with this PR to 4 to at least validate that the code runs in the CI environment.

**Comment by paulmillr** [comment]
How does the content look to you overall? Are you cool with releasing 2.0 "very soon" (maybe we add sth else to the board too)?

**Comment by es128** [comment]
Haven't had time yet to evaluate any more than just at a surface level. I'd want to try to validate no behavior change - too bad we don't have good tests to tell us.

I'm ok with releasing with no change in functionality, although it doesn't really do anything to benefit users - just evolving the project.

I still want to eventually re-do the whole thing from the ground up.

**Comment by paulmillr** [comment]
OK great. Should definitely bring us more long-term contributors. :+1:

**Pull request merged**
