### PR TITLE
New architecture

### PR DESCRIPTION
**Pull request by paulmillr**

### CODE REVIEW

**Comment by paulmillr** [comment]
It would be great to start introducing tests with the release. Want to make sure 2.11 is more stable than 2.10.

**Comment by jacksonrayhamilton** [comment]
Looks like this needs rebasing, and tests.  Anything else to move this towards merging?

Also, if you could specify what needs tested, I could write some of these tests.  e.g., provide an outline of the specs you want, like:

- the compiler
  - should compile from one format to another
  - should compile from format A to B and then from format B to C

And so on.  Also, an overview of what this release accomplishes would be helpful.

**Comment by shvaikalesh** [comment]
@jacksonrayhamilton This PR is not done yet. According to my time estimations, the fastest approach is to release breaking `3.0`. What is left is to replace `deppack` with `rollup` and make current tests pass, and then figure out how to make e2e tests a joy to write.

**Comment by jacksonrayhamilton** [comment]
Thanks for the update @shvaikalesh.  Do you have an idea of what scenarios e2e tests might cover?

**Comment by shvaikalesh** [comment]
@jacksonrayhamilton I will start with covering most error-prone (that was broken on my watch) logic, like merging `plugins.on|off` in `overrides` (see #826), merging `joinTo` and `entryPoints`, choosing plugins based on `env` etc. Hopefully, with some breaking changes in `3.0` there will be less such pain points.

**Comment by lydell** [comment]
@jacksonrayhamilton There are also some ideas for tests in #1642.

**Comment by rudi-c** [comment]
Hi @paulmillr @shvaikalesh, since this PR looks like a big one but currently isn't seeing progress, would it be possible to quickly write a summary of the features it will bring, API changes, and bugs it will fix? Right now Typescript is quite hard to use with Brunch and I have ideas on how to fix that, but I want to make sure to avoid doing duplicate and/or conflicting changes with the intended direction of Brunch.

**Comment by explicitcall** [comment]
Hi @paulmillr @shvaikalesh, big +1 to @rudi-c comment, would be awesome to have some kind of roadmap for 3.0 release to understand what's coming. This would greatly help Brunch users in navigating existing issues and give better understanding if it's worth submitting new pull requests. 
Thanks in advance.

**Comment by Tim15** [comment]
I am wondering if this will bring support for alternate bundlers like Rollup.

If we were to support Rollup, it would need some changes in the pipeline architecture. Since Rollup really shines with ES6 modules and tree-shaking, we would have some plugins run beforehand, and some (like Babel) run after the bundle is generated. Also, I wonder if Rollup would have better or worse performance than deppack. I'm not sure what types of optimizations they have done as far as atomic rebuilding.

It would be interesting to define a bundler API, that any new bundler could implement.

If I can help in any way, just ping me. I'm very excited to see what 3.0 brings!

**Comment by StarpTech** [comment]
Hi, what's the status of this PR? The last commit is 1 year old and it seems inactive to me.

**Comment by Tim15** [comment]
Any updates on this PR and version 3.0? Is the project still under development/being maintained?

**Comment by jacksonrayhamilton** [comment]
@Tim15 I guess the entire Brunch team must have been eaten by wolves on the same night.  What a shame, I liked this project.

**Comment by paulmillr** [comment]
Unfortunately we are focusing on more value creation; through other projects — at this particular moment. Sad we cannot spend more time with Brunch. Any help would be greatly appreciated.

**Comment by kavdev** [comment]
@paulmillr has that changed at all? What needs to be done to get this merged?

**Comment by clarknelson** [comment]
when are we getting this bad boy

**Comment by paulmillr** [comment]
The status is simple: someone needs to take it over and finish the work (at least ~1 month 2h every day).

**Comment by seanstrom** [comment]
@paulmillr What would be needed to work on to finish the work? Was there a feature list for 3.0, or a breaking change list?

**Comment by paulmillr** [comment]
@seanstrom do you want to work on it? We can discuss this together. The idea is: an ultra-modern build tool that keeps Brunch simplicity, and increases it — while having everything required for 2020 web app dev.

**Comment by seanstrom** [comment]
@paulmillr Yeah I would like to work on this. What's currently missing from Brunch that would be needed for 2020 app development? An example feature could be Code Splitting, or would that be something that is configured with a plugin?

**Comment by paulmillr** [comment]
Code splitting indeed! We need to have first-class support for that. 

I think there should be some ways to simplify the config even more, and incorporate threading aka workers. This may increase the build speed 3x. We’d also want some kind of persistent file system caching, to increase speed of cold builds. 

One commonly requested feature is an ability to easily replace script and css paths inside index.html with git commit hashes or similar suffixes.

Cache & workers are simple. Conceptual changes, script path updates are harder.

**Comment by paulmillr** [comment]
I want to release a version that keeps compatibility, while reducing the package size twice or more. See #1848. It will be named 3.0; the current PR is deferring until we figure out the requirements.

**Comment by paulmillr** [comment]
Alright, we have a stable build in pull request #1848. Let's move over there.

**Pull request closed without merging**
